### ISSUE TITLE
Zero StartMin, EndMin omitempty on Restriction

### ISSUE THREAD

**Issue by imamfzn** [opsgenie/opsgenie-go-sdk-v2#11]
Hei, i'm trying to use create rotation (with time restrict) from the sdk. But there error:
`Error occurred with Status code: 422, Message: Request body is not processable. Please check the errors., Took: 0.005000, RequestId: efeac8ca-a11f-4e5d-aceb-5eb3ca8cefab, Error Detail: map[endMin:may not be null startMin:may not be null]`

I set the restrict `StartMin`, and `EndMin` to `0`. But i think it was omitted by `json: omitempty`.
I think the `StartMin`, and `EndMin` should not set as omitempty, because it makes no value when requesting to the opsgenie api.

I think, we must change / remove the `omitempty` tags of `StartMin` and `EndMin` on [Restriction struct](https://github.com/opsgenie/opsgenie-go-sdk-v2/blob/master/og/entity.go#L275-L282)

Thanks!

**Comment by cglrkn** [comment]
We created an issue on our side to fix that problem that you are having. We will inform you when it is fixed. Thanks for your contribution.

**Comment by ErenKizilay** [comment]
The problem should be resolved with this https://github.com/opsgenie/opsgenie-go-sdk-v2/pull/16
Thanks for the report.
