### ISSUE TITLE
Logrus related compile time error

### ISSUE THREAD

**Issue by aswinmprabhu** [opsgenie/opsgenie-go-sdk-v2#12]
```
# github.com/moira-alert/moira/vendor/github.com/opsgenie/opsgenie-go-sdk-v2/client
vendor/github.com/opsgenie/opsgenie-go-sdk-v2/client/client.go:179:14: conf.Logger.SetFormatter undefined (type *logrus.Logger has no field or method SetFormatter)
vendor/github.com/opsgenie/opsgenie-go-sdk-v2/client/client.go:249:23: client.Config.Logger.GetLevel undefined (type *logrus.Logger has no field or method GetLevel)
vendor/github.com/opsgenie/opsgenie-go-sdk-v2/client/config.go:90:14: undefined: logrus.TraceLevel
```
I am getting the above error when trying to complie code that uses the `github.com/opsgenie/opsgenie-go-sdk-v2/client` package. I am using govendor to vendor my dependencies. Any ideas on what might be the issue?

**Comment by borovskyav** [comment]
Good support guys...

**Comment by cglrkn** [comment]
Can you please provide more information about the env; the golang version you using and does the logurs exists in your GOPATH?

**Comment by aswinmprabhu** [comment]
Already solved it! Turns out it was a dependency mismatch issue. You were using a newer version of logrus. Thanks anyway!
