### ISSUE TITLE
Fail to create a disabled Heartbeat

### ISSUE THREAD

**Issue by rk295** [opsgenie/opsgenie-go-sdk-v2#15]
I think this is similar to #11,  when I create a new `heartbeat.AddRequest` with `Enabled: false`, the JSON Marshaller drops the field from the returned JSON, which in results in a payload rejection from the API, leading to this error:

```
ERRO[2019-09-10T11:24:44.601831+01:00] Error occurred with Status code: 422, Message: Request body is not processable. Please check the errors., Took: 0.029000, RequestId: cd7bec9b-......, Error Detail: map[enabled:may not be null] 
```

I believe this is the [intended](https://github.com/golang/go/issues/13284#issuecomment-157288425) behaviour of the Go JSON Marshaller because the struct definition has `omitempty` for that field.

**Comment by ErenKizilay** [comment]
It should be resolved with v1.0.3
