### ISSUE TITLE
Incident Create request: description or tags can't be sent via due wrong json tag

### ISSUE THREAD

**Issue by astreter** [opsgenie/opsgenie-go-sdk-v2#36]
Here is a misprint:
https://github.com/opsgenie/opsgenie-go-sdk-v2/blob/cf7378aab3925aaa51886edf29da75be18cfad92/incident/request.go#L37

Correct json tag for Tags field must be `tags` but not `description` which already exists.

**Comment by MeralBusraTekinsen** [comment]
We have released v1.1.1 for this fix. Thanks.
