### ISSUE TITLE
API Key is leaked when a client is created

### ISSUE THREAD

**Issue by ctompkinson** [opsgenie/opsgenie-go-sdk-v2#7]
Currently when a client is created it prints a log, this contains information about the API Key and other client details.

Ideally this wouldn't be logged at all and would be left up to the consuming application, but there are security implications by automatically logging the API key that is leaked into whatever log aggregation when the client is created, without anyway to disable this.

#6

**Comment by ErenKizilay** [comment]
we have removed apiKey from the logs. Thanks for the warning.
