### ISSUE TITLE
List Schedule not contains Id for Rotation

### ISSUE THREAD

**Issue by imamfzn** [opsgenie/opsgenie-go-sdk-v2#8]
Hello, I have a personal problem when using this sdk :(.
My case, i need to use List Schedule from the sdk. I need to get the detail of each rotation on each schedule, but there lack of field i needed from the rotation field. I need the Id attribute of the rotation from List Schedule result.

From Rotations type using og.Rotation that not contain Id Rotation. So Rotation from List Schedule result will not contain the Id of Rotation, but i need it :(.

From [this api documentation](https://docs.opsgenie.com/docs/schedule-api#section-list-schedules), the rest api for list schedule rotation contains the id rotation. I think all we need is to add an Id field in og.Rotation, so the schedule result always contains Rotation Id's.

My solution purpose is to change [this lines](https://github.com/opsgenie/opsgenie-go-sdk-v2/blob/master/og/entity.go#L15-L24) to :

```go
type Rotation struct {
	client.BaseRequest
	Id              string           `json:"id,omitempty"`
	Name            string           `json:"name,omitempty"`
	StartDate       *time.Time       `json:"startDate,omitempty"`
	EndDate         *time.Time       `json:"endDate,omitempty"`
	Type            RotationType     `json:"type,omitempty"`
	Length          uint32           `json:"length,omitempty"`
	Participants    []Participant    `json:"participants,omitempty"`
	TimeRestriction *TimeRestriction `json:"timeRestriction,omitempty"`
}
```

I hope you can consider my problem and my propose solution.

Thanks :)

**Comment by cglrkn** [comment]
@imamfzn We added the "id" field to the rotation. Thanks for your contribution.
